version: "3.7"
services:
  app:
    container_name: flask-app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: flask-app:lastest
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    restart: always
    networks:
      - internal


networks:
  internal:
    driver: bridge
